# FIRA Data Dictionary - Part 1: User & Org + Applicant models
# Field tuple: (field, type, required, description, allowed_values, populated_by, fk, algo_role)

ORG_TABLES = [
{
"name": "User",
"purpose": "Master account table for every actor (applicant, employer, agency user, FIRA staff). Row = one login identity; role drives all permissions and the matching candidate pool.",
"fields": [
("id", "String", "Yes", "Primary key (CUID) uniquely identifying the account across all roles.", "System-generated CUID", "System", "-", "System"),
("email", "String", "Yes", "Login email; unique per account. Used for sign-in, recovery and identity reference.", "Valid email; UNIQUE", "All roles (self at signup)", "-", "Access"),
("password", "String", "Yes", "Login credential (stored hashed, bcrypt).", "Hashed string", "System", "-", "Access"),
("name", "String", "Yes", "Display full name shown in dashboards, endorsements and ranked candidate lists.", "Free text", "All roles (self)", "-", "Profile"),
("role", "String", "Yes", "Actor type; drives role-based access control on every API route and UI view. ALSO the first filter of the matching candidate pool (only role='applicant' rows are scored).", "super_admin | staff | applicant | local_agency | international_agency | employer  (default when commenting schema: admin is legacy)", "System (assigned at signup)", "-", "Core Input (pool filter)"),
("phone", "String?", "No", "Primary contact number of the account holder.", "Free text", "All roles (self)", "-", "Profile"),
("avatar", "String?", "No", "URL/path of the profile photo.", "File path or URL", "All roles (self)", "-", "Profile"),
("isActive", "Boolean", "Yes", "Soft-activation flag. Inactive users cannot log in and are EXCLUDED from the matching candidate pool.", "true (default) | false", "FIRA Staff", "-", "Core Input (pool filter)"),
("isApproved", "Boolean", "Yes", "Approval flag. Applicants must be approved (true) to appear in the matching pool; employer/agency accounts also gated by this flag.", "false (default) | true", "FIRA Staff", "-", "Core Input (pool filter)"),
("createdAt", "DateTime", "Yes", "Account creation timestamp.", "Auto now()", "System", "-", "System"),
("updatedAt", "DateTime", "Yes", "Last modification timestamp.", "Auto on update", "System", "-", "System"),
]},
{
"name": "Agency",
"purpose": "Recruitment agency organizations (local PH agencies and international agencies) that can create job orders and endorse candidates.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("name", "String", "Yes", "Registered agency name.", "Free text", "FIRA Staff", "-", "Profile"),
("agencyType", "String", "Yes", "Segment of the agency; determines job-creation rights and visibility scope.", "local (default) | international", "FIRA Staff", "-", "Access"),
("address", "String?", "No", "Street address of the agency office.", "Free text", "FIRA Staff", "-", "Profile"),
("city", "String?", "No", "City of the agency office.", "Free text", "FIRA Staff", "-", "Profile"),
("country", "String?", "No", "Country where the agency operates.", "Free text", "FIRA Staff", "-", "Profile"),
("licenseNo", "String?", "No", "Government recruitment license number (e.g. DMW license). Used for compliance verification.", "Free text", "FIRA Staff", "-", "Profile"),
("phone", "String?", "No", "Agency contact number.", "Free text", "FIRA Staff", "-", "Profile"),
("email", "String?", "No", "Agency contact email.", "Free text", "FIRA Staff", "-", "Profile"),
("website", "String?", "No", "Agency website URL.", "URL", "FIRA Staff", "-", "Profile"),
("isActive", "Boolean", "Yes", "Soft-activation flag for the agency record.", "true (default) | false", "FIRA Staff", "-", "Access"),
("isApproved", "Boolean", "Yes", "Compliance approval flag; gates agency participation in workflows.", "false (default) | true", "FIRA Staff", "-", "Access"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
("updatedAt", "DateTime", "Yes", "Last modification timestamp.", "Auto on update", "System", "-", "System"),
]},
{
"name": "AgencyMember",
"purpose": "Join table linking User accounts to Agencies, with the member's functional role inside the agency (unique per user+agency).",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("userId", "String", "Yes", "The user account that belongs to the agency.", "-", "System", "-> User.id (cascade)", "System"),
("agencyId", "String", "Yes", "The agency the user belongs to.", "-", "System", "-> Agency.id", "System"),
("role", "String", "Yes", "Functional role of the member inside the agency.", "admin | recruiter | processor | deployment_officer | member (default: member)", "FIRA Staff / Agency admin", "-", "Access"),
("joinedAt", "DateTime", "Yes", "Timestamp when the member joined the agency.", "Auto now()", "System", "-", "System"),
]},
{
"name": "EmployerProfile",
"purpose": "Company profile attached 1:1 to a User with role='employer'. Owner of job orders and the receiving party of endorsements.",
"fields": [
("id", "String", "Yes", "Primary key (CUID); referenced as employerId by JobOrder and Endorsement.", "System-generated CUID", "System", "-", "System"),
("userId", "String", "Yes", "Owning login account; unique (1 employer account = 1 company profile).", "-", "System", "-> User.id (cascade), UNIQUE", "System"),
("companyName", "String", "Yes", "Registered employer/company name; shown on job orders and endorsements.", "Free text", "Employer", "-", "Profile"),
("companyAddress", "String?", "No", "Company office address.", "Free text", "Employer", "-", "Profile"),
("country", "String", "Yes", "Country where the company operates; destination country of its job orders.", "Free text", "Employer", "-", "Context Input"),
("industry", "String?", "No", "Industry sector of the company.", "Free text", "Employer", "-", "Context Input"),
("contactPerson", "String?", "No", "Named contact person for recruitment matters.", "Free text", "Employer", "-", "Profile"),
("contactEmail", "String?", "No", "Recruitment contact email.", "Free text", "Employer", "-", "Profile"),
("contactPhone", "String?", "No", "Recruitment contact phone.", "Free text", "Employer", "-", "Profile"),
("website", "String?", "No", "Company website URL.", "URL", "Employer", "-", "Profile"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
("updatedAt", "DateTime", "Yes", "Last modification timestamp.", "Auto on update", "System", "-", "System"),
]},
]

APPLICANT_TABLES = [
{
"name": "ApplicantProfile",
"purpose": "THE core matching-side table: 1:1 with every job-seeking User. Holds personal data, travel-document readiness, work preferences and the resume text consumed by the matching algorithm.",
"fields": [
("id", "String", "Yes", "Primary key (CUID); referenced by all child tables as applicantId.", "System-generated CUID", "System", "-", "System"),
("userId", "String", "Yes", "Owning login account; unique (1 applicant account = 1 profile).", "-", "System", "-> User.id (cascade), UNIQUE", "System"),
("firstName", "String", "Yes", "Legal first name.", "Free text", "Applicant", "-", "Profile"),
("middleName", "String?", "No", "Legal middle name.", "Free text", "Applicant", "-", "Profile"),
("lastName", "String", "Yes", "Legal last name.", "Free text", "Applicant", "-", "Profile"),
("suffixName", "String?", "No", "Name suffix (Jr., Sr., III).", "Free text", "Applicant", "-", "Profile"),
("gender", "String?", "No", "Declared gender; some destination roles are gender-specific (privacy-sensitive).", "male | female", "Applicant", "-", "Context Input"),
("birthDate", "DateTime?", "No", "Date of birth; source for age-derived eligibility rules.", "ISO date", "Applicant", "-", "Context Input"),
("birthPlace", "String?", "No", "Place of birth.", "Free text", "Applicant", "-", "Profile"),
("nationality", "String", "Yes", "Nationality of the applicant.", "Any (default: Filipino)", "Applicant", "-", "Context Input"),
("civilStatus", "String?", "No", "Declared civil status.", "single | married | widowed | separated", "Applicant", "-", "Context Input"),
("religion", "String?", "No", "Declared religion; relevant for destination-country placement rules.", "Free text", "Applicant", "-", "Context Input"),
("height", "String?", "No", "Declared height (free-text units).", "Free text", "Applicant", "-", "Context Input"),
("weight", "String?", "No", "Declared weight (free-text units).", "Free text", "Applicant", "-", "Context Input"),
("address", "String?", "No", "Street address in the Philippines.", "Free text", "Applicant", "-", "Profile"),
("city", "String?", "No", "City / municipality of residence.", "Free text", "Applicant", "-", "Context Input"),
("province", "String?", "No", "Province of residence.", "Free text", "Applicant", "-", "Context Input"),
("region", "String?", "No", "Philippine region of residence (placement-origin analytics).", "Free text", "Applicant", "-", "Context Input"),
("zipCode", "String?", "No", "Postal code of residence.", "Free text", "Applicant", "-", "Profile"),
("phone", "String?", "No", "Primary mobile number.", "Free text", "Applicant", "-", "Profile"),
("altPhone", "String?", "No", "Alternate contact number.", "Free text", "Applicant", "-", "Profile"),
("email", "String?", "No", "Contact email (may differ from login email).", "Free text", "Applicant", "-", "Profile"),
("applicantType", "String?", "No", "Worker segment; aligns with JobOrder.category for track-specific matching (domestic vs skills).", "domestic_helper | skills_professional", "Applicant", "-", "Context Input (segment)"),
("householdTasks", "String?", "No", "JSON string array of household task capabilities; skill-style signal for domestic helper roles.", 'JSON array of: cooking | cleaning | laundry | childcare | elderly_care | gardening | pet_care', "Applicant", "-", "Context Input"),
("passportNo", "String?", "No", "Passport number.", "Free text", "Applicant", "-", "Context Input"),
("passportExpiry", "DateTime?", "No", "Passport expiry date; readiness signal for deployment.", "ISO date", "Applicant", "-", "Context Input"),
("passportStatus", "String?", "No", "Passport readiness state.", "valid | expired | processing | none", "Applicant", "-", "Context Input"),
("hasVisa", "Boolean", "Yes", "Whether the applicant currently holds any visa.", "false (default) | true", "Applicant", "-", "Context Input"),
("visaCountry", "String?", "No", "Country of the held visa.", "Free text", "Applicant", "-", "Context Input"),
("visaType", "String?", "No", "Type/category of the held visa.", "Free text", "Applicant", "-", "Context Input"),
("visaStatus", "String?", "No", "Visa readiness state.", "Free text (default: none)", "Applicant", "-", "Context Input"),
("visaExpiry", "DateTime?", "No", "Visa expiry date.", "ISO date", "Applicant", "-", "Context Input"),
("medicalStatus", "String?", "No", "Pre-employment medical exam state; deployment-readiness gate.", "passed | failed | scheduled | none", "Applicant / Agency", "-", "Context Input"),
("medicalExpiry", "DateTime?", "No", "Medical certificate expiry date.", "ISO date", "Applicant / Agency", "-", "Context Input"),
("highestEducation", "String?", "No", "Highest educational attainment (free text).", "Free text", "Applicant", "-", "Context Input"),
("yearsExperience", "Int?", "No", "Self-reported total years of relevant work experience. DIRECT algorithm feature: exp_factor = min(years/10, 1).", "Integer >= 0", "Applicant", "-", "Core Input"),
("preferredCountry", "String?", "No", "Destination country the applicant prefers; usable for preference-aligned ranking.", "Free text", "Applicant", "-", "Context Input"),
("preferredJob", "String?", "No", "Job/role the applicant prefers.", "Free text", "Applicant", "-", "Context Input"),
("salaryExpectation", "String?", "No", "Expected salary (free text, not numeric) - needs parsing before use in salary-fit features.", "Free text", "Applicant", "-", "Context Input"),
("availabilityDate", "String?", "No", "Earliest availability to start work (free text).", "Free text", "Applicant", "-", "Context Input"),
("resumeText", "String?", "No", "Full plain-text resume. PRIMARY algorithm feature for semantic similarity against JobOrder.description.", "Long text", "Applicant (or AI resume parse)", "-", "Core Input"),
("emergencyName", "String?", "No", "Emergency contact person name.", "Free text", "Applicant", "-", "Profile"),
("emergencyRelation", "String?", "No", "Relationship to emergency contact.", "Free text", "Applicant", "-", "Profile"),
("emergencyPhone", "String?", "No", "Emergency contact number.", "Free text", "Applicant", "-", "Profile"),
("formStep", "Int", "Yes", "Multi-step profile wizard progress marker.", "Integer step index (default: 0)", "System", "-", "System"),
("isComplete", "Boolean", "Yes", "Profile completeness flag. RECOMMENDED algorithm gate (not yet enforced in pool query).", "false (default) | true", "System", "-", "Lifecycle"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
("updatedAt", "DateTime", "Yes", "Last modification timestamp.", "Auto on update", "System", "-", "System"),
]},
{
"name": "ApplicantEducation",
"purpose": "Educational background entries (1 applicant : N education records).",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("institution", "String", "Yes", "School / university name.", "Free text", "Applicant", "-", "Context Input"),
("degree", "String", "Yes", "Degree or level obtained.", "Free text", "Applicant", "-", "Context Input"),
("fieldOfStudy", "String?", "No", "Major / specialization.", "Free text", "Applicant", "-", "Context Input"),
("startYear", "Int", "Yes", "Year started.", "4-digit year", "Applicant", "-", "Context Input"),
("endYear", "Int", "Yes", "Year finished.", "4-digit year", "Applicant", "-", "Context Input"),
("honors", "String?", "No", "Academic honors received.", "Free text", "Applicant", "-", "Profile"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantExperience",
"purpose": "Work history entries (1 applicant : N experience records); supports verification and experience-based scoring extensions.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("company", "String", "Yes", "Employer / company name.", "Free text", "Applicant", "-", "Context Input"),
("position", "String", "Yes", "Job title held.", "Free text", "Applicant", "-", "Context Input"),
("country", "String?", "No", "Country where the work was performed (overseas experience signal).", "Free text", "Applicant", "-", "Context Input"),
("startDate", "DateTime", "Yes", "Employment start date.", "ISO date", "Applicant", "-", "Context Input"),
("endDate", "DateTime?", "No", "Employment end date (null if current).", "ISO date", "Applicant", "-", "Context Input"),
("isCurrent", "Boolean", "Yes", "Whether this is the current job.", "false (default) | true", "Applicant", "-", "Context Input"),
("description", "String?", "No", "Duties and achievements; supplementary text for semantic matching.", "Long text", "Applicant", "-", "Context Input"),
("monthlySalary", "String?", "No", "Salary received (free text).", "Free text", "Applicant", "-", "Profile"),
("employerContact", "String?", "No", "Reference contact for verification.", "Free text", "Applicant", "-", "Profile"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantSkill",
"purpose": "Discrete skill entries; `name` is the DIRECT algorithm feature matched against JobOrder.requiredSkills (case-insensitive exact overlap).",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("name", "String", "Yes", "Skill name (free text, matched case-insensitively). Candidate for a controlled vocabulary.", "Free text (e.g. cooking, elderly care)", "Applicant", "-", "Core Input"),
("level", "String", "Yes", "Self-assessed proficiency level of the skill.", "beginner | intermediate (default) | advanced | expert", "Applicant", "-", "Context Input"),
("yearsExperience", "Int?", "No", "Years of experience with this specific skill; usable as confidence weight.", "Integer >= 0", "Applicant", "-", "Context Input"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantLanguage",
"purpose": "Language proficiencies; supports destination-country language requirements (e.g. Arabic/Hebrew/English).",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("language", "String", "Yes", "Language name.", "Free text (e.g. English, Tagalog, Arabic)", "Applicant", "-", "Context Input"),
("proficiency", "String", "Yes", "Overall proficiency level.", "basic | conversational (default) | intermediate | advanced | fluent | native", "Applicant", "-", "Context Input"),
("speaking", "String?", "No", "Speaking proficiency (optional breakdown).", "Same scale as proficiency; blank = not set", "Applicant", "-", "Context Input"),
("reading", "String?", "No", "Reading proficiency (optional breakdown).", "Same scale as proficiency; blank = not set", "Applicant", "-", "Context Input"),
("writing", "String?", "No", "Writing proficiency (optional breakdown).", "Same scale as proficiency; blank = not set", "Applicant", "-", "Context Input"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantCertification",
"purpose": "Certifications and credentials (TESDA, NC II, caregiving, etc.) with expiry tracking for validity screening.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("name", "String", "Yes", "Certification name.", "Free text", "Applicant", "-", "Context Input"),
("issuingBody", "String?", "No", "Issuing organization.", "Free text", "Applicant", "-", "Context Input"),
("issuedDate", "DateTime?", "No", "Date issued.", "ISO date", "Applicant", "-", "Context Input"),
("expiryDate", "DateTime?", "No", "Expiry date (validity screening).", "ISO date", "Applicant", "-", "Context Input"),
("credentialId", "String?", "No", "Certificate/credential ID for verification.", "Free text", "Applicant", "-", "Profile"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantReference",
"purpose": "Character/professional references supplied by the applicant; used in verification, not in scoring.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("name", "String", "Yes", "Reference person name.", "Free text", "Applicant", "-", "Profile"),
("company", "String?", "No", "Reference's company.", "Free text", "Applicant", "-", "Profile"),
("position", "String?", "No", "Reference's position.", "Free text", "Applicant", "-", "Profile"),
("phone", "String?", "No", "Reference contact number.", "Free text", "Applicant", "-", "Profile"),
("email", "String?", "No", "Reference contact email.", "Free text", "Applicant", "-", "Profile"),
("relationship", "String?", "No", "Relationship to the reference.", "Free text", "Applicant", "-", "Profile"),
("yearsKnown", "String?", "No", "Years the reference has known the applicant.", "Free text", "Applicant", "-", "Profile"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantDocument",
"purpose": "Uploaded supporting documents (resume, passport, certificates) with verification flag; a natural pre-deployment eligibility gate.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("documentType", "String", "Yes", "Kind of document uploaded (free text; 'resume' and 'other' observed in code).", "Free text (e.g. resume, passport, certificate)", "Applicant", "-", "Context Input"),
("fileName", "String", "Yes", "Original file name.", "Free text", "Applicant", "-", "Profile"),
("filePath", "String?", "No", "Storage path of the uploaded file.", "File path", "System", "-", "System"),
("fileSize", "Int?", "No", "File size in bytes.", "Integer bytes", "System", "-", "System"),
("mimeType", "String?", "No", "File MIME type.", "e.g. application/pdf", "System", "-", "System"),
("isVerified", "Boolean", "Yes", "Whether FIRA has verified the document.", "false (default) | true", "FIRA Staff", "-", "Lifecycle"),
("uploadedAt", "DateTime", "Yes", "Upload timestamp.", "Auto now()", "System", "-", "System"),
]},
{
"name": "ApplicantTraining",
"purpose": "Trainings attended (e.g. TESDA courses) with hour counts; supplementary skill evidence.",
"fields": [
("id", "String", "Yes", "Primary key (CUID).", "System-generated CUID", "System", "-", "System"),
("applicantId", "String", "Yes", "Owning applicant profile.", "-", "System", "-> ApplicantProfile.id (cascade)", "System"),
("trainingName", "String", "Yes", "Training program name.", "Free text", "Applicant", "-", "Context Input"),
("institution", "String?", "No", "Training provider.", "Free text", "Applicant", "-", "Context Input"),
("startDate", "DateTime?", "No", "Training start date.", "ISO date", "Applicant", "-", "Context Input"),
("endDate", "DateTime?", "No", "Training end date.", "ISO date", "Applicant", "-", "Context Input"),
("hours", "Int?", "No", "Total training hours.", "Integer", "Applicant", "-", "Context Input"),
("createdAt", "DateTime", "Yes", "Record creation timestamp.", "Auto now()", "System", "-", "System"),
]},
]
